# skqw theme configuration

# site setting
rss: /atom.xml
favicon: "images/favicon.ico"

# style setting
monochrome: true

# view setting
avatar: https://cn.gravatar.com/avatar/35fef74d731255cd569c2c2b0b9e87e4?s=200
avatarLink: /about
maxContentWidth: 800px # set the main content column's max-width property. keep it blank to unlimited the width
copyright: 'Michael Bromley' # the copyright text in the footer, could be richtext

# sidebar navigator structure
# It's a list with item that is also list.
# The item of first level list means a group of links,
# and the item of the second level list means exactly a link.
# A link item is an object whit two properties: 'name' for displaying and 'link' for redirecting.
# A link starts with http/https would be rendered as a tag with 'target="_blank"' .
# There are also some special link items representing in string: 'categories', 'tags' and 'archives'
nav:
  -
    -
      name: 'User Guide'
    -
      name: 'Getting Started'
      url: '/getting-started'
    -
      name: 'How To Guides'
      url: '/how-to'
  -
    -
      name: 'Developer Guide'
    -
      name: 'Getting Started'
      url: '/developer-guide-getting-started'
    -
      name: 'Parameters'
      url: '/parameters'
    -
      name: 'Using Three.js'
      url: '/using-three-js'
    -
      name: 'API Reference'
      url: '/api-reference'
    -
      name: 'skqw-core'
      url: '/skqw-core-module'
  -
    -
      name: 'Links'
    -
      name: 'SKQW on Github'
      url: 'https://github.com/michaelbromley/skqw'
    -
      name: '@michlbrmly'
      url: 'https://twitter.com/michlbrmly'


# duoshuo shortname
# refer to http://duoshuo.com
# If you use disqus then you should set disqus_shortname in your site config and disable duoshuo here.
# You also need to set 'comments' to true in the front-matter
#duoshuo: sprabbit

# jiathis share id
# refer to http://jiathis.com
#jiathis: 1589291

# open graph
twitter: "@michlbrmly"
google_plus:
fb_admins:
fb_app_id:

# analytics ids
google_analytics:
baidu_statistics:

# default creative commons
# There are 6 kinds of combination and place 'none' to disable.
# - by
# - by-sa
# - by-nd
# - by-nc
# - by-nc-sa
# - by-nc-nd
# - none
# This setting could be overwritten in the front matter of a post.
# More details in https://creativecommons.org
cc: by-sa

# FancyBox / PhotoSwipe
# Although it is called fancybox, we use PhotoSwipe instead.
# Check http://photoswipe.com
fancybox: true    # enable fancybox/photoswipe rendering
# photoswipe: true  # the same
